Completed first pass of .adoc files and revised template
aws-quickstart/quickstart-eks-snyk pull request #4
Opened 2020-10-22 02:10 UTC by DelfinGala

*Description of changes:*
Updated partner_editable content and eks-snyk.template.yaml. Note that there are embedded //TODO comments.

It seems that large portions of text were entered into the boilerplate section of the repo. All of those items should be relocated to partner_editable. I made changes to several boilerplate files, but I won't commit/push them until we sort out this issue.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-10-26 19:58 UTC, jaymccon requested changes
I've removed the redundant files that were the source of most of the `TODO`. Added review comments for everything else.

2020-11-06 01:37 UTC, DelfinGala commented on templates/eks-snyk.template.yaml
> +    Description: 'Snyk Kubernetes Integration ID. This must be obtained from the Snyk console. For more information, see https://support.snyk.io/hc/en-us/articles/360003916158-Install-the-Snyk-contro
Kubernetes should definitely be capitalized. I'm not sure why I capitalized "integration." Seems like a mistake on my part.

2020-11-06 01:41 UTC, DelfinGala commented on docs/partner_editable/_settings.adoc
> +:partner-product-name: Snyk Controller for Amazon EKS on the AWS Cloud
True, but this is the value that goes into the title, where it should be capitalized.

2020-11-06 01:42 UTC, DelfinGala commented on docs/partner_editable/architecture.adoc
> +//TODO This list should capture everything in the diagram. It's currently missing most of the items I see in the diagram.
Fair enough.

2020-11-06 01:43 UTC, DelfinGala commented on docs/partner_editable/licenses.adoc
> +This Quick Start requires a Snyk license. For more information, see https://aws.amazon.com/marketplace/pp/B085VGM85Q?qid=1590170928622&sr=0-1&ref_=srh_res_product_title[Snyk: Developer-First Security
Why is it necessary to call out AWS Marketplace?

2020-11-06 01:45 UTC, DelfinGala commented on templates/eks-snyk.template.yaml
> +    Description: 'Snyk Kubernetes Integration ID. This must be obtained from the Snyk console. For more information, see https://support.snyk.io/hc/en-us/articles/360003916158-Install-the-Snyk-contro
Kubernetes should be capitalized. "Integration" can be set in lowercase.

2020-11-06 19:58 UTC, merged